server:
  port: 8886

---
spring:
  profiles: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8887/eureka/

---
spring:
  profiles: kubernetes

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8080/eureka/
