server:
  port: 8886


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: http://eureka-server:8080/eureka/

---
spring:
  profiles: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8080/eureka/

---
spring:
  profiles: kubernetes

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: http://eureka-server:8080/eureka/

